### ISSUE TITLE
第一篇靠北文會抓不到前篇 ID

### ISSUE THREAD

**Issue by s3131212** [BirkhoffLee/AnonyPages#2]
因為這個好棒棒系統的 Hashtag 是抓前一篇的 Hashtag ID +1 當做該篇靠北文的 ID ，但是當沒有前一篇文，也就是這是第一篇文章時，就會出現「在處理您的文章時發生了錯誤。」，但是文章有被送出去，且沒有 Hashtag ID ，必須靠管理員手動放上去，才能保證以後運作正常。

**Comment by BirkhoffLee** [comment]
之前有改過這個 bug 但是忘記 push 上來
我改一下

**Comment by BirkhoffLee** [comment]
fixed

**Comment by BirkhoffLee** [comment]
話說要怎麼 reference 到 commit
